import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { artifactBookData } from '../../public/app/src/data/artifactBookData';
import { bookChapters } from '../../public/app/src/data/book';
import { extractCanonicalJournalPrompts } from '../../public/app/src/data/canonicalPrompts';

const compact = (value: unknown) => String(value ?? '').replace(/\r\n/g, '\n').trim();

const sectionText = (section: typeof artifactBookData.chapters[number]['sections'][number]) =>
  section.blocks
    .flatMap((block) => {
      if ('items' in block && Array.isArray(block.items)) return block.items.map((item) => compact(item));
      return 'text' in block ? [compact(block.text)] : [];
    })
    .filter(Boolean)
    .join('\n\n');

const chapterById = new Map(bookChapters.map((chapter) => [chapter.id, chapter]));
const coverChapter = chapterById.get('capa-digital');
const cover = artifactBookData.meta.cover;

const chapters = [
  {
    id: 'capa-digital',
    kind: 'cover',
    title: cover.title,
    groupId: coverChapter?.groupId ?? 'frontmatter',
    audioTracks: coverChapter?.audioTracks ?? [],
    journalPrompts: [],
    sections: [{
      id: 'capa-digital--abertura',
      title: 'Capa digital',
      audioId: null,
      text: [cover.imprint, cover.title, cover.tagline, cover.author].join('\n\n'),
    }],
  },
  ...artifactBookData.chapters.map((artifactChapter) => {
    const readerChapter = chapterById.get(artifactChapter.id);
    return {
      id: artifactChapter.id,
      kind: artifactChapter.kind ?? readerChapter?.kind ?? 'chapter',
      title: artifactChapter.title,
      groupId: readerChapter?.groupId ?? '',
      audioTracks: readerChapter?.audioTracks ?? [],
      journalPrompts: artifactChapter.kind === 'caderno'
        ? extractCanonicalJournalPrompts(artifactChapter.id, artifactChapter.sections)
        : [],
      sections: artifactChapter.sections.map((section) => ({
        id: section.id,
        title: section.title,
        audioId: section.audioId ?? null,
        text: sectionText(section),
      })),
    };
  }),
];

const index = {
  meta: artifactBookData.meta,
  generatedFrom: 'public/app/src/data/artifactBookData.ts + public/app/src/data/book.ts',
  chapters,
};

const serialized = JSON.stringify(index, null, 2);
const ids = chapters.flatMap((chapter) => [chapter.id, ...chapter.sections.map((section) => section.id)]);
const duplicateIds = ids.filter((id, indexOfId) => ids.indexOf(id) !== indexOfId);
const emptySections = chapters.flatMap((chapter) =>
  chapter.sections.filter((section) => !section.text.trim()).map((section) => `${chapter.id}:${section.id}`),
);

if (serialized.includes('\uFFFD')) throw new Error('Canonical index contains Unicode replacement characters.');
if (duplicateIds.length) throw new Error(`Duplicate canonical IDs: ${Array.from(new Set(duplicateIds)).join(', ')}`);
if (emptySections.length) throw new Error(`Empty canonical sections: ${emptySections.join(', ')}`);

const output = [
  '/* Auto-generated by scripts/generate-canonical-index.ts. Do not edit manually. */',
  '',
  `export const OPDDS_CANONICAL_BOOK_INDEX = ${serialized} as const;`,
  '',
].join('\n');

writeFileSync(resolve(process.cwd(), 'src/igent/opdds-canonical-book-data.ts'), output, 'utf8');
console.log(`Canonical index generated: ${chapters.length} chapters, ${ids.length - chapters.length} sections.`);
