export const pilar6 = {
  chapter: 6,
  title: "Pilar 6: Desejo — Eu posso querer sem me punir",
  // Nome sugerido para o arquivo de áudio no servidor: capitulo-06.mp3
  audioUrl: "https://opoderdosdesacreditados.online/media/audio/livro/capitulo-06.mp3",
  content: [
    "🔻 TRÍADE DA RECONSTRUÇÃO",
    "Autorização: Eu posso querer sem me punir",
    " ",
    "Manifesto de Abertura — Quando Querer se Torna Culpa",
    "O desejo costuma ser tratado como perigo. Algo que precisa ser contido, domesticado ou justificado. Desde cedo, aprendemos que querer demais é excesso, querer errado é desvio, querer para si é egoísmo. Assim, o desejo deixa de ser força vital e passa a ser fonte de culpa.",
    "Este pilar não fala de desejo como impulso inconsequente nem como falta de controle. Ele fala do desejo como expressão legítima de vida — e do que acontece quando essa expressão é reprimida, distorcida ou moralizada.",
    "Para muitos desacreditados, desejar nunca foi simples. Querer significava arriscar rejeição, frustração ou punição. Em algum momento, foi mais seguro não querer — ou querer apenas o que era permitido. Reconhecer isso é o início de uma reconstrução mais honesta.",
    " ",
    "Narrativa Profunda — Quando o Desejo Precisa se Disfarçar",
    "O desejo não desaparece quando é reprimido. Ele se desloca. Assume outras formas. Torna-se ansiedade, compulsão, comparação constante ou insatisfação difusa. O corpo continua querendo, mesmo quando a mente aprendeu a negar.",
    "Muitas pessoas aprendem a desejar de maneira indireta. Querem através do outro. Querem aquilo que parece aceitável. Querem o que promete pertencimento, status ou alívio imediato. Poucas aprendem a reconhecer o próprio desejo sem vergonha.",
    "O desacreditado costuma viver essa tensão. Sente vontade, mas se censura. Quer algo diferente, mas se pune por isso. Oscila entre repressão e excesso, entre negação e fuga. Não por fraqueza moral, mas porque nunca aprendeu a sustentar o desejo sem se atacar.",
    " ",
    "CONSCIÊNCIA — Reconhecer Desejos Negados e Deslocados",
    "A consciência, neste pilar, começa quando você se permite perguntar o que realmente quer — sem corrigir a resposta imediatamente. Sem comparar com o que é esperado. Sem moralizar.",
    "Muitos desejos foram negados cedo demais. Outros foram deslocados para áreas mais aceitáveis: trabalho, consumo, relações vazias. Alguns viraram compulsões. Outros foram enterrados junto com a ideia de que querer era perigoso.",
    "Reconhecer esses movimentos é perceber que o desejo não é inimigo. Ele é indicador. Mostra onde há vida, onde há falta, onde algo quer existir.",
    "A consciência devolve algo essencial: você pode querer sem precisar se justificar o tempo todo.",
    " ",
    "JULGAMENTO — Moralizar o Querer",
    "Quando o desejo não é reconhecido, ele é julgado. A pessoa passa a se acusar por querer mais, por querer diferente, por não se satisfazer com o que tem. Surge a sensação de inadequação constante.",
    "O mundo reforça esse julgamento ao exaltar controle, autocontenção e renúncia como virtudes absolutas. Pouco se fala sobre o custo psíquico de negar o próprio desejo por tempo demais.",
    "O desacreditado aprende a se punir pelo que sente vontade de viver. Aprende a achar que há algo errado em si por querer o que quer. Assim, o desejo vira campo de batalha interna.",
    "Separar desejo de culpa é um passo delicado, mas necessário. Querer não é falhar. Reprimir-se constantemente, sim, cobra um preço alto.",
    " ",
    "PRESENÇA — Sustentar o Desejo com Responsabilidade",
    "Presença, neste pilar, não é satisfazer todos os desejos nem agir impulsivamente. É reconhecer o que se quer sem se destruir por isso. É sustentar o desejo com responsabilidade, sem negá-lo nem idealizá-lo.",
    "Quando o desejo é acolhido, ele perde a urgência destrutiva. Deixa de exigir descarga imediata. Passa a ser escutado, elaborado, integrado.",
    "Sustentar o desejo exige maturidade emocional. Exige aceitar frustrações, limites e escolhas. Mas tudo isso só é possível quando o desejo deixa de ser tratado como culpa.",
    "Você pode querer — e ainda assim escolher como agir. Uma coisa não anula a outra.",
    " ",
    "Carta de Sustentação — A Quem Aprendeu a Não Querer",
    "Talvez você tenha aprendido a reduzir desejos para caber. Talvez tenha silenciado vontades para manter vínculos. Talvez tenha transformado desejo em culpa para não lidar com a frustração.",
    "Este pilar não te pede que realize tudo o que quer. Te pede apenas honestidade interna. Te pede que pare de se atacar por sentir vontade de viver algo diferente.",
    "Querer não te torna inadequado.",
    " ",
    "Âncora Prática — Microação de Autorização",
    "Hoje, observe um desejo sem corrigi-lo.",
    "Não planeje. Não execute. Apenas reconheça.",
    "Quando surgir a culpa, repita internamente:",
    "“Eu posso querer sem me punir.”",
    "Essa frase não exige ação.",
    "Mas devolve verdade a quem sente."
  ]
};